# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x7jlHen3IM-KR5WYR47qeR8Xrsw6dCmo
"""

def even_or_odd(n):
    if n % 2 == 0:
        return "Even"
    else:
        return "Odd"


def add_all(numbers):
    total = 0
    for num in numbers:
        total += num
    return total


print(even_or_odd(4))
print(even_or_odd(7))

print(add_all([1, 2, 3, 4, 5]))